projects:
  oshigw:
    schemaPath: frontend/src/graphql/schema.json
    includes:
      - frontend/src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - frontend/src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: frontend/src/API.ts
        docsFilePath: frontend/src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
