// Additional types for custom index queries (@index) not generated by Amplify codegen
// This file augments ./API generated types without modifying the auto-generated file.
// If Amplify later generates these types natively, you can delete this file.

import './API';

declare module './API' {
  // Key condition inputs normally generated when an @index queryField is present.
  export type ModelStringKeyConditionInput = {
    eq?: string | null;
    le?: string | null;
    lt?: string | null;
    ge?: string | null;
    gt?: string | null;
    between?: Array<string | null> | null;
    beginsWith?: string | null;
  };
  export type ModelIntKeyConditionInput = {
    eq?: number | null;
    le?: number | null;
    lt?: number | null;
    ge?: number | null;
    gt?: number | null;
    between?: Array<number | null> | null;
  };

  // tasksByProject (projectId + createdAt sort key)
  export type TasksByProjectQueryVariables = {
    projectId: string;
    createdAt?: ModelStringKeyConditionInput | null;
    sortDirection?: ModelSortDirection | null;
    filter?: ModelTaskFilterInput | null;
    limit?: number | null;
    nextToken?: string | null;
  };
  export type TasksByProjectQuery = {
    tasksByProject?: ModelTaskConnection | null;
  };

  // tasksByProjectNumberPath (projectId + numberPath sort key)
  export type TasksByProjectNumberPathQueryVariables = {
    projectId: string;
    numberPath?: ModelStringKeyConditionInput | null;
    sortDirection?: ModelSortDirection | null;
    filter?: ModelTaskFilterInput | null;
    limit?: number | null;
    nextToken?: string | null;
  };
  export type TasksByProjectNumberPathQuery = {
    tasksByProjectNumberPath?: ModelTaskConnection | null;
  };

  // tasksByParent (parentTaskId + sequence sort key)
  export type TasksByParentQueryVariables = {
    parentTaskId: string;
    sequence?: ModelIntKeyConditionInput | null;
    sortDirection?: ModelSortDirection | null;
    filter?: ModelTaskFilterInput | null;
    limit?: number | null;
    nextToken?: string | null;
  };
  export type TasksByParentQuery = {
    tasksByParent?: ModelTaskConnection | null;
  };
}
